/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tp9;

import javafx.application.Application;
import javafx.geometry.Pos;
import javafx.stage.Stage;
// import javafx.scene.control.Button;
// import javafx.scene.layout.StackPane;
import javafx.scene.layout.VBox;
import javafx.scene.Scene;
// import javafx.event.ActionEvent;
// import javafx.event.EventHandler;
// import javafx.scene.control.Label;

public class App extends Application{
    
    @Override
    public void start(Stage stage){
        
        Layarsatu pertama = new Layarsatu(stage);
        pertama.show();
        
    }
    
    public static void main(String[] args) {
        launch(args);
    }
}

